import type { Metadata } from 'next';
import '../styles/reset.scss';
import '../styles/base.scss';

import NextAuthSessionProvider from '../provider/NextAuthSessionProvider';

/** 기본 레이아웃  */

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// router에 접근하기 위해서는 useRouter를 사용해야 합니다.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="section">
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </div>
      </body>
    </html>
  );
}
