import type { Metadata } from 'next';
import Script from 'next/script';

import '../styles/reset.scss';
import '../styles/base.scss';

import NextAuthSessionProvider from '../provider/NextAuthSessionProvider';

/** 기본 레이아웃  */

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="section">
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </div>
      </body>
      <Script
        src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.1/kakao.min.js"
        integrity="sha384-kDljxUXHaJ9xAb2AzRd59KxjrFjzHa5TAoFQ6GbYTCAG0bjM55XohjjDT7tDDC01"
        crossOrigin="anonymous"
      />
    </html>
  );
}
